//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom
    {
        public int id_client { get; set; }
        public int id_category { get; set; }
        public string city { get; set; }
        public int minPrice { get; set; }
        public int maxPrice { get; set; }
        public Nullable<int> num_rooms { get; set; }
        public Nullable<int> num_people { get; set; }
        public Nullable<int> floor { get; set; }
        public Nullable<int> mr { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual clients clients { get; set; }
    }
}
