//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id_item { get; set; }
        public int id_category { get; set; }
        public int id_client { get; set; }
        public bool status { get; set; }
    
        public virtual apartments apartments { get; set; }
        public virtual categories categories { get; set; }
        public virtual clients clients { get; set; }
        public virtual tzimers tzimers { get; set; }
        public virtual units units { get; set; }
    }
}
