//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectDBEntities : DbContext
    {
        public projectDBEntities()
            : base("name=projectDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<renter> renter { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tzimers> tzimers { get; set; }
        public virtual DbSet<units> units { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<custom> custom { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<orders> orders { get; set; }
    }
}
